(function() {var h=!0,k=null,n=!1,o=parseInt,p=document,q=chrome;function r(a,b){return a.type=b}function s(a,b){return a.target=b}
var t="appendChild",u="push",aa="removed",w="indexOf",ba="createElement",ca="handleEvent",y="type",z="length",da="propertyIsEnumerable",A="prototype",ea="split",fa="target",B="call",C="",ga=" ",ha="(\\d*)(\\D*)",ia="-",ja=".",ka="[object Array]",la="[object Function]",na="[object Window]",oa="_",D="array",pa="call",qa="change",E="checkbox",ra="event",sa="false",ta="fieldset",ua="for",va="form",F="function",wa="g",xa="input",ya="label",za="null",Aa="number",Ba="object",Ca="on",Da="option-form",Ea=
"splice",Fa="string",Ga="true",Ha="window",G=this;function H(a){var b=typeof a;if(b==Ba)if(a){if(a instanceof Array)return D;if(a instanceof Object)return b;var c=Object[A].toString[B](a);if(c==na)return Ba;if(c==ka||typeof a[z]==Aa&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[da]&&!a[da](Ea))return D;if(c==la||"undefined"!=typeof a[B]&&"undefined"!=typeof a[da]&&!a[da](pa))return F}else return za;else if(b==F&&"undefined"==typeof a[B])return Ba;return b}
var I="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),Ia=0;function Ja(a,b){function c(){}c.prototype=b[A];a.k=b[A];a.prototype=new c};q.experimental={};q.experimental.rlz={};q.experimental.rlz.recordProductEvent=function(){};var J=Array[A],Ka=J[w]?function(a,b,c){return J[w][B](a,b,c)}:function(a,b,c){c=c==k?0:0>c?Math.max(0,a[z]+c):c;if(typeof a==Fa)return typeof b!=Fa||1!=b[z]?-1:a[w](b,c);for(;c<a[z];c++)if(c in a&&a[c]===b)return c;return-1},La=J.forEach?function(a,b,c){J.forEach[B](a,b,c)}:function(a,b,c){for(var e=a[z],g=typeof a==Fa?a[ea](C):a,d=0;d<e;d++)d in g&&b[B](c,g[d],d,a)};var K,Ma,Na,Oa;function Pa(){return G.navigator?G.navigator.userAgent:k}Oa=Na=Ma=K=n;var Qa;if(Qa=Pa()){var Ra=G.navigator;K=0==Qa[w]("Opera");Ma=!K&&-1!=Qa[w]("MSIE");Na=!K&&-1!=Qa[w]("WebKit");Oa=!K&&!Na&&"Gecko"==Ra.product}var Sa=K,L=Ma,M=Oa,Ta=Na,Ua;
a:{var Va=C,N;if(Sa&&G.opera)var Wa=G.opera.version,Va=typeof Wa==F?Wa():Wa;else if(M?N=/rv\:([^\);]+)(\)|;)/:L?N=/MSIE\s+([^\);]+)(\)|;)/:Ta&&(N=/WebKit\/(\S+)/),N)var Xa=N.exec(Pa()),Va=Xa?Xa[1]:C;if(L){var Ya,Za=G.document;Ya=Za?Za.documentMode:void 0;if(Ya>parseFloat(Va)){Ua=C+Ya;break a}}Ua=Va}var $a=Ua,ab={};
function O(a){var b;if(!(b=ab[a])){b=0;for(var c=(C+$a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,C)[ea](ja),e=(C+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,C)[ea](ja),g=Math.max(c[z],e[z]),d=0;0==b&&d<g;d++){var f=c[d]||C,i=e[d]||C,l=RegExp(ha,wa),j=RegExp(ha,wa);do{var v=l.exec(f)||[C,C,C],m=j.exec(i)||[C,C,C];if(0==v[0][z]&&0==m[0][z])break;b=((0==v[1][z]?0:o(v[1],10))<(0==m[1][z]?0:o(m[1],10))?-1:(0==v[1][z]?0:o(v[1],10))>(0==m[1][z]?0:o(m[1],10))?1:0)||((0==v[2][z])<(0==m[2][z])?-1:(0==v[2][z])>(0==m[2][z])?
1:0)||(v[2]<m[2]?-1:v[2]>m[2]?1:0)}while(0==b)}b=ab[a]=0<=b}return b}var bb={};function cb(){return bb[9]||(bb[9]=L&&!!p.documentMode&&9<=p.documentMode)};function db(a){db[ga](a);return a}db[ga]=function(){};!L||cb();var eb=!L||cb();L&&O("8");!Ta||O("528");M&&O("1.9b")||L&&O("8")||Sa&&O("9.5")||Ta&&O("528");M&&!O("8")||L&&O("9");function P(){}P[A].l=n;P[A].g=function(){this.l||(this.l=h,this.c())};P[A].c=function(){this.p&&fb.apply(k,this.p)};function fb(a){for(var b=0,c=arguments[z];b<c;++b){var e=arguments[b],g=e,d=H(g);d==D||d==Ba&&typeof g[z]==Aa?fb.apply(k,e):e&&typeof e.g==F&&e.g()}};function Q(a,b){r(this,a);s(this,b);this.a=this[fa]}Ja(Q,P);Q[A].c=function(){delete this[y];delete this[fa];delete this.a};Q[A].d=n;Q[A].o=h;function R(a,b){a&&gb(this,a,b)}Ja(R,Q);s(R[A],k);R[A].n=k;function gb(a,b,c){var e=r(a,b[y]);Q[B](a,e);s(a,b[fa]||b.srcElement);a.a=c;if((c=b.relatedTarget)&&M)try{db(c.nodeName)}catch(g){}a.n=b;delete a.o;delete a.d}R[A].c=function(){R.k.c[B](this);s(this,k);this.a=k};function S(){}var hb=0;S[A].key=0;S[A].removed=n;S[A].c=n;S[A].handleEvent=function(a){return this.a?this.f[B](this.i||this.src,a):this.f[ca][B](this.f,a)};var T={},U={},V={},W={};
function ib(a,b,c,e,g){if(b){if(H(b)==D){for(var d=0;d<b[z];d++)ib(a,b[d],c,e,g);return k}var e=!!e,f=U;b in f||(f[b]={b:0,e:0});f=f[b];e in f||(f[e]={b:0,e:0},f.b++);var f=f[e],i=a[I]||(a[I]=++Ia),l;f.e++;if(f[i]){l=f[i];for(d=0;d<l[z];d++)if(f=l[d],f.f==c&&f.i==g){if(f[aa])break;return l[d].key}}else l=f[i]=[],f.b++;d=jb();d.src=a;var j=f=new S;if(H(c)==F)j.a=h;else if(c&&c[ca]&&H(c[ca])==F)j.a=n;else throw Error("Invalid listener argument");j.f=c;j.d=d;j.src=a;r(j,b);j.capture=!!e;j.i=g;j.c=n;
j.key=++hb;j.removed=n;c=f.key;d.key=c;l[u](f);T[c]=f;V[i]||(V[i]=[]);V[i][u](f);a.addEventListener?(a==G||!a.m)&&a.addEventListener(b,d,e):a.attachEvent(b in W?W[b]:W[b]=Ca+b,d);return c}throw Error("Invalid event type");}function jb(){var a=kb,b=eb?function(c){return a[B](b.src,b.key,c)}:function(c){c=a[B](b.src,b.key,c);if(!c)return c};return b}
function lb(a){if(!T[a])return n;var b=T[a];if(b[aa])return n;var c=b.src,e=b[y],g=b.d,d=b.capture;c.removeEventListener?(c==G||!c.m)&&c.removeEventListener(e,g,d):c.detachEvent&&c.detachEvent(e in W?W[e]:W[e]=Ca+e,g);c=c[I]||(c[I]=++Ia);g=U[e][d][c];if(V[c]){var f=V[c],i=Ka(f,b);0<=i&&J.splice[B](f,i,1);0==f[z]&&delete V[c]}b.removed=h;g.j=h;mb(e,d,c,g);delete T[a];return h}
function mb(a,b,c,e){if(!e.h&&e.j){for(var g=0,d=0;g<e[z];g++)e[g][aa]?e[g].d.src=k:(g!=d&&(e[d]=e[g]),d++);e.length=d;e.j=n;0==d&&(delete U[a][b][c],U[a][b].b--,0==U[a][b].b&&(delete U[a][b],U[a].b--),0==U[a].b&&delete U[a])}}function nb(a,b,c,e,g){var d=1,b=b[I]||(b[I]=++Ia);if(a[b]){a.e--;a=a[b];a.h?a.h++:a.h=1;try{for(var f=a[z],i=0;i<f;i++){var l=a[i];l&&!l[aa]&&(d&=ob(l,g)!==n)}}finally{a.h--,mb(c,e,b,a)}}return Boolean(d)}function ob(a,b){var c=a[ca](b);a.c&&lb(a.key);return c}
function kb(a,b){if(!T[a])return h;var c=T[a],e=c[y],g=U;if(!(e in g))return h;var g=g[e],d,f;if(!eb){var i;if(!(i=b))a:{i=[Ha,ra];for(var l=G;d=i.shift();)if(l[d]!=k)l=l[d];else{i=k;break a}i=l}d=i;i=h in g;l=n in g;if(i){if(0>d.keyCode||void 0!=d.returnValue)return h;a:{var j=n;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(v){j=h}if(j||void 0==d.returnValue)d.returnValue=h}}j=new R;gb(j,d,this);d=h;try{if(i){for(var m=[],ma=j.a;ma;ma=ma.parentNode)m[u](ma);f=g[h];f.e=f.b;for(var x=m[z]-1;!j.d&&
0<=x&&f.e;x--)j.a=m[x],d&=nb(f,m[x],e,h,j);if(l){f=g[n];f.e=f.b;for(x=0;!j.d&&x<m[z]&&f.e;x++)j.a=m[x],d&=nb(f,m[x],e,n,j)}}else d=ob(c,j)}finally{m&&(m.length=0),j.g()}return d}e=new R(b,this);try{d=ob(c,e)}finally{e.g()}return d};!L||cb();!M&&!L||L&&cb()||M&&O("1.9.1");L&&O("9");"ScriptEngine"in G&&"JScript"==G.ScriptEngine()&&(G.ScriptEngineMajorVersion(),G.ScriptEngineMinorVersion(),G.ScriptEngineBuildVersion());function X(a){this.d=a;this.a=[]}Ja(X,P);var pb=[];X[A].removeAll=function(){La(this.a,lb);this.a.length=0};X[A].c=function(){X.k.c[B](this);this.removeAll()};X[A].handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function qb(){X[B](this)}Ja(qb,X);var sb=rb,Y=["tblf","htsa","initOptions"],Z=G;!(Y[0]in Z)&&Z.execScript&&Z.execScript("var "+Y[0]);for(var $;Y[z]&&($=Y.shift());)!Y[z]&&void 0!==sb?Z[$]=sb:Z=Z[$]?Z[$]:Z[$]={};var tb=k,ub={"pref-navigate-new-tab":{type:E,defaultValue:Ga},"pref-enable-https":{type:E,defaultValue:sa},"pref-show-search-button-on-select":{type:E,defaultValue:Ga}};function rb(){tb=new qb;p.body[t](vb())}
function vb(){var a=p[ba](va);a.id=Da;for(var b in ub){var c=p[ba](ta),e=ub[b];switch(e[y]){case E:var g=p[ba](xa);r(g,E);g.name=b;g.id=b;g.checked=(window.localStorage.getItem(b)||e.defaultValue)!=sa;e=p[ba](ya);e.setAttribute(ua,b);e[t](p.createTextNode(q.i18n.getMessage(b[ea](ia).join(oa))));c[t](g);c[t](e);var e=tb,d=qa,f=wb;H(d)!=D&&(pb[0]=d,d=pb);for(var i=0;i<d[z];i++)e.a[u](ib(g,d[i],f||e,n,e.d||e))}a[t](c)}return a}
function wb(a){var a=a[fa],b=a.name;switch(a[y]){case E:window.localStorage.setItem(b,a.checked?Ga:sa)}};})()
